"""
补充字库数据（84 个诗词推荐缺字）

为诗词库 recommend_chars 中缺失的字补齐命理数据，
使每首诗词都有足够的可用字进行同源组名。

字段说明：
- char: 汉字
- radical: 部首
- kangxi_strokes: 康熙笔画（五格数理用，参考值，繁体字形计画）
- simplified_strokes: 简体笔画
- wuxing: 五行
- luck: 吉凶
- gender: 适合性别（男/女/中）
- meaning: 简要释义
- shuowen: 《说文解字》原文（简化字；未收或存疑者注明）
- detail: 字源与起名寓意的综合释义

拼音、声调由 pypinyin 在合并脚本中自动生成。
"""

EXTRA_CHARS = [
    {"char": "丝", "radical": "糸", "kangxi_strokes": 12, "simplified_strokes": 5, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "蚕丝，象征细腻、绵长、情谊", "shuowen": "蚕所吐也。从二糸。", "detail": "本义为蚕丝。丝缕绵长不绝，喻情意之绵长、心思之细腻。起名寓意细腻温柔、情深意长。"},
    {"char": "中", "radical": "丨", "kangxi_strokes": 4, "simplified_strokes": 4, "wuxing": "土", "luck": "吉", "gender": "中",
     "meaning": "正中、不偏不倚，象征公正、和谐", "shuowen": "内也。从口，丨上下通。", "detail": "本义为正中、内部。不偏不倚谓之「中」，含中正、中庸之道。起名寓意正直公道、不偏不倚。"},
    {"char": "久", "radical": "丿", "kangxi_strokes": 3, "simplified_strokes": 3, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "长久、恒久，象征持久、恒心", "shuowen": "从后灸之，象人两胫后有距也。", "detail": "本义为时间长、持久。「久」含恒久、绵长之意，喻持之以恒。起名寓意持之以恒、历久弥坚。"},
    {"char": "伊", "radical": "亻", "kangxi_strokes": 6, "simplified_strokes": 6, "wuxing": "土", "luck": "吉", "gender": "女",
     "meaning": "彼、他，亦指水名，象征温婉、美好", "shuowen": "殷圣人阿衡，尹治天下者。从人，从尹。", "detail": "本义为第三人称，后多用于人名。古有伊尹贤相、伊人佳人之典。起名寓意温婉贤淑、美好可人。"},
    {"char": "修", "radical": "亻", "kangxi_strokes": 10, "simplified_strokes": 9, "wuxing": "金", "luck": "吉", "gender": "男",
     "meaning": "修养、修长，象征进取、美好", "shuowen": "饰也。从彡，攸声。", "detail": "本义为修饰、整治，引申为修身养性、学习进取。「修」含修养身心、完善自我之意。起名寓意修身立德、追求卓越。"},
    {"char": "健", "radical": "亻", "kangxi_strokes": 11, "simplified_strokes": 10, "wuxing": "木", "luck": "吉", "gender": "男",
     "meaning": "强健、健康，象征活力、刚强", "shuowen": "伉也。从人，建声。", "detail": "本义为强健有力。引申为健康、刚强、康健。「健」喻体格强健、精神饱满。起名寓意健康强壮、奋发向上。"},
    {"char": "兰", "radical": "艹", "kangxi_strokes": 23, "simplified_strokes": 5, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "兰花，象征高洁、典雅、芬芳", "shuowen": "香草也。从艸，阑声。", "detail": "本义为兰草，古以「兰」为香草，喻君子之德、高洁之品。成语「芝兰玉树」喻优秀子弟。起名寓意高洁典雅、芬芳馥郁。"},
    {"char": "关", "radical": "门", "kangxi_strokes": 19, "simplified_strokes": 6, "wuxing": "木", "luck": "中", "gender": "中",
     "meaning": "关口、关键，象征重要、守护", "shuowen": "以木横持门户也。从门，丱声。", "detail": "本义为门闩、关口。引申为关键、重要。「关」喻守要扼冲、举足轻重。起名寓意至关重要、担当重任。"},
    {"char": "内", "radical": "冂", "kangxi_strokes": 4, "simplified_strokes": 4, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "内部、内心，象征涵养、深沉", "shuowen": "入也。从冂，自外而入也。", "detail": "本义为内部、里面。引申为内心、涵养。「内」含内敛、内秀之意。起名寓意内蕴深厚、含而不露。"},
    {"char": "凌", "radical": "冫", "kangxi_strokes": 10, "simplified_strokes": 10, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "冰凌、升高，象征高远、清寒高洁", "shuowen": "冰出也。从冫，夌声。", "detail": "本义为冰凌、积冰，引申为升高、逾越。「凌云」喻志向高远。起名寓意高洁凌霜、志存高远。"},
    {"char": "匪", "radical": "匚", "kangxi_strokes": 10, "simplified_strokes": 10, "wuxing": "水", "luck": "中", "gender": "中",
     "meaning": "非、不是，古义为文采斐然", "shuowen": "器，似竹筐。从匚，非声。", "detail": "本义为竹筐器皿。古有「有匪君子」之句，「匪」通「斐」，喻文采斐然。起名寓意文采出众、器宇不凡。"},
    {"char": "千", "radical": "十", "kangxi_strokes": 3, "simplified_strokes": 3, "wuxing": "金", "luck": "吉", "gender": "中",
     "meaning": "数目，象征众多、宏大", "shuowen": "十百也。从十，从人。", "detail": "本义为数目字，十百为千。「千」引申为众多、广大，如「千祥云集」。起名寓意前程广阔、气象万千。"},
    {"char": "博", "radical": "十", "kangxi_strokes": 12, "simplified_strokes": 12, "wuxing": "水", "luck": "吉", "gender": "男",
     "meaning": "广博、丰富，象征渊博、宽广", "shuowen": "大通也。从十，尃声。", "detail": "本义为广大、通达，引申为渊博、丰富。「博」喻学识广博、胸怀宽广。起名寓意博学多才、宽厚包容。"},
    {"char": "和", "radical": "口", "kangxi_strokes": 8, "simplified_strokes": 8, "wuxing": "水", "luck": "吉", "gender": "中",
     "meaning": "和谐、温和，象征平和、融洽", "shuowen": "相应也。从口，禾声。", "detail": "本义为声音相应、和谐。「和」喻和睦、温和、协调，如「和而不同」。起名寓意温和平顺、与人为善。"},
    {"char": "嘉", "radical": "口", "kangxi_strokes": 14, "simplified_strokes": 14, "wuxing": "木", "luck": "吉", "gender": "中",
     "meaning": "美好、嘉许，象征优秀、喜庆", "shuowen": "美也。从壴，加声。", "detail": "本义为美好、吉祥。「嘉」含嘉许、嘉祥之意，如「嘉言懿行」。起名寓意美好出众、吉祥喜庆。"},
    {"char": "天", "radical": "大", "kangxi_strokes": 4, "simplified_strokes": 4, "wuxing": "火", "luck": "吉", "gender": "男",
     "meaning": "天空、上天，象征高远、广阔", "shuowen": "颠也。至高无上，从一、大。", "detail": "本义为头顶、天空，引申为至高无上、广阔无边。「天」喻高远博大。起名寓意胸怀宽广、志向高远。"},
    {"char": "夭", "radical": "大", "kangxi_strokes": 4, "simplified_strokes": 4, "wuxing": "火", "luck": "凶", "gender": "女",
     "meaning": "草木茂盛，亦含夭折义，慎用", "shuowen": "屈也。从大，象形。", "detail": "本义为草木屈曲茂盛，「桃之夭夭」喻美好。但「夭」亦含夭折之义，起名需谨慎，多与「桃夭」连用取茂盛美好意。"},
    {"char": "姝", "radical": "女", "kangxi_strokes": 9, "simplified_strokes": 9, "wuxing": "金", "luck": "吉", "gender": "女",
     "meaning": "美好，象征女子美丽贤淑", "shuowen": "好也。从女，朱声。", "detail": "本义为美好、美女。「静女其姝」喻女子美丽娴静。起名寓意美丽大方、贤淑优雅。"},
    {"char": "娟", "radical": "女", "kangxi_strokes": 10, "simplified_strokes": 10, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "娟秀，象征美丽、清秀", "shuowen": "婵娟也。从女，肙声。", "detail": "本义为姿态美好、娟秀。「娟」喻女子清秀美丽、举止优雅。起名寓意秀丽动人、温婉可亲。"},
    {"char": "婵", "radical": "女", "kangxi_strokes": 15, "simplified_strokes": 14, "wuxing": "金", "luck": "吉", "gender": "女",
     "meaning": "婵娟，象征美好、优雅", "shuowen": "婵娟，态也。从女，单声。", "detail": "本义为姿态美好，「婵娟」多喻明月与美女。起名寓意优雅美好、清新脱俗。"},
    {"char": "寻", "radical": "寸", "kangxi_strokes": 12, "simplified_strokes": 6, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "寻找、探究，象征求索、进取", "shuowen": "绎理也。从工口，从又寸。", "detail": "本义为探寻、求索。「寻」含探索、追求之意。起名寓意勤于求索、孜孜不倦。"},
    {"char": "少", "radical": "小", "kangxi_strokes": 4, "simplified_strokes": 4, "wuxing": "金", "luck": "中", "gender": "中",
     "meaning": "年少、不多，象征年轻、朝气", "shuowen": "不多也。从小，丿声。", "detail": "本义为数量不多，引申为年少、年轻。「少年」喻朝气蓬勃。起名寓意年轻有为、朝气蓬勃。"},
    {"char": "年", "radical": "干", "kangxi_strokes": 6, "simplified_strokes": 6, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "年份、年岁，象征丰收、长久", "shuowen": "谷孰也。从禾，千声。", "detail": "本义为谷熟、年成，引申为岁月、年龄。「年」喻丰收、长久。起名寓意年丰人寿、岁月静好。"},
    {"char": "山", "radical": "山", "kangxi_strokes": 3, "simplified_strokes": 3, "wuxing": "土", "luck": "吉", "gender": "男",
     "meaning": "山峰，象征稳重、高大、坚毅", "shuowen": "宣也。宣气散，生万物，有石而高。象形。", "detail": "本义为山峰。「山」喻稳重、高大、坚毅，如「仁者乐山」。起名寓意稳重如山、品格高尚。"},
    {"char": "得", "radical": "彳", "kangxi_strokes": 11, "simplified_strokes": 11, "wuxing": "金", "luck": "吉", "gender": "中",
     "meaning": "获得、得到，象征有所成就", "shuowen": "行有所得也。从彳，㝵声。", "detail": "本义为获得、得到。「得」含有所得、如愿以偿之意。起名寓意心想事成、有所成就。"},
    {"char": "意", "radical": "心", "kangxi_strokes": 13, "simplified_strokes": 13, "wuxing": "土", "luck": "吉", "gender": "中",
     "meaning": "心意、意志，象征志向、情意", "shuowen": "志也。从心察言而知意也。从心，从音。", "detail": "本义为心意、意志。「意」含志向、情意、意境之意。起名寓意意志坚定、情深意远。"},
    {"char": "愉", "radical": "忄", "kangxi_strokes": 12, "simplified_strokes": 12, "wuxing": "金", "luck": "吉", "gender": "女",
     "meaning": "愉悦、快乐，象征开朗、和悦", "shuowen": "薄也。从心，俞声。", "detail": "本义为快乐、愉悦。「愉」含和悦、舒畅之意。起名寓意开朗乐观、心情愉悦。"},
    {"char": "扬", "radical": "扌", "kangxi_strokes": 12, "simplified_strokes": 6, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "扬起、发扬，象征奋发、声名", "shuowen": "飞举也。从手，昜声。", "detail": "本义为举起、飞扬，引申为发扬、宣扬。「扬」含奋发向上、声名远扬之意。起名寓意积极进取、名扬四方。"},
    {"char": "故", "radical": "攵", "kangxi_strokes": 9, "simplified_strokes": 9, "wuxing": "木", "luck": "中", "gender": "中",
     "meaning": "缘故、旧时，象征念旧、厚重", "shuowen": "使为之也。从攴，古声。", "detail": "本义为缘故、原因，引申为故旧、旧时。「故」含念旧、厚重之意。起名较少单用，多与典出相连。"},
    {"char": "新", "radical": "斤", "kangxi_strokes": 13, "simplified_strokes": 13, "wuxing": "金", "luck": "吉", "gender": "中",
     "meaning": "崭新、更新，象征创新、朝气", "shuowen": "取木也。从斤，亲声。", "detail": "本义为伐木取新，引申为崭新、更新。「其命维新」喻革故鼎新。起名寓意开拓创新、焕然一新。"},
    {"char": "春", "radical": "日", "kangxi_strokes": 9, "simplified_strokes": 9, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "春天，象征生机、温暖、希望", "shuowen": "推也。从艸，从日，屯声。", "detail": "本义为春季，万物生发。「春」喻生机勃勃、温暖和煦。起名寓意春意盎然、充满希望。"},
    {"char": "月", "radical": "月", "kangxi_strokes": 4, "simplified_strokes": 4, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "月亮，象征清辉、柔和、美好", "shuowen": "阙也。太阴之精。象形。", "detail": "本义为月亮。「月」喻清辉皎洁、柔和美好，如「花好月圆」。起名寓意温婉清雅、光彩照人。"},
    {"char": "材", "radical": "木", "kangxi_strokes": 7, "simplified_strokes": 7, "wuxing": "木", "luck": "吉", "gender": "男",
     "meaning": "木材、材质，象征才能、栋梁", "shuowen": "木梃也。从木，才声。", "detail": "本义为木材，引申为才能、材质。「材」喻人才、栋梁之材。起名寓意才学出众、可成大器。"},
    {"char": "枫", "radical": "木", "kangxi_strokes": 13, "simplified_strokes": 8, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "枫树，象征坚韧、美好、相思", "shuowen": "木也。从木，风声。", "detail": "本义为枫树，秋叶红艳。古以「枫」寄相思，今喻坚毅美好。起名寓意坚韧不拔、红红火火。"},
    {"char": "江", "radical": "氵", "kangxi_strokes": 7, "simplified_strokes": 6, "wuxing": "水", "luck": "吉", "gender": "男",
     "meaning": "江河，象征宽广、奔流、气势", "shuowen": "水。出蜀湔氐徼外岷山，入海。从水，工声。", "detail": "本义为长江，后泛指大河。「江」喻气势磅礴、胸怀宽广。起名寓意心胸开阔、气度不凡。"},
    {"char": "沅", "radical": "氵", "kangxi_strokes": 8, "simplified_strokes": 7, "wuxing": "水", "luck": "吉", "gender": "中",
     "meaning": "沅水，象征清澈、灵动、源远流长", "shuowen": "水。出牂牁故且兰，东北入江。从水，元声。", "detail": "本义为沅水，楚地之河。《九歌》有「沅有芷兮」。起名寓意源远流长、清新灵动。"},
    {"char": "河", "radical": "氵", "kangxi_strokes": 9, "simplified_strokes": 8, "wuxing": "水", "luck": "吉", "gender": "男",
     "meaning": "河流，象征奔流、宽广、浩荡", "shuowen": "水。出敦煌塞外昆仑山，发源注海。从水，可声。", "detail": "本义为黄河，后泛指河流。「河」喻浩荡奔流、源远流长。起名寓意气度恢弘、勇往直前。"},
    {"char": "洲", "radical": "氵", "kangxi_strokes": 10, "simplified_strokes": 9, "wuxing": "水", "luck": "吉", "gender": "中",
     "meaning": "水中小岛，象征独立、清幽", "shuowen": "水中可居曰州。从重川。", "detail": "本义为水中陆地。「关关雎鸠，在河之洲」喻清幽之地。起名寓意独立清雅、卓尔不群。"},
    {"char": "浪", "radical": "氵", "kangxi_strokes": 11, "simplified_strokes": 10, "wuxing": "水", "luck": "中", "gender": "中",
     "meaning": "波浪，象征奔放、自由、浪漫", "shuowen": "沧浪水也。从水，良声。", "detail": "本义为波浪。「沧浪」含清浊之辨，亦喻自由奔放。起名寓意洒脱不羁、志向远大。"},
    {"char": "淇", "radical": "氵", "kangxi_strokes": 12, "simplified_strokes": 11, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "淇水，象征清澈、温婉", "shuowen": "水。出河内共北山，东入河。从水，其声。", "detail": "本义为淇水，《诗经》多咏之。「淇」喻清澈温婉。起名寓意清纯灵动、温婉动人。"},
    {"char": "淑", "radical": "氵", "kangxi_strokes": 12, "simplified_strokes": 11, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "贤淑、善良，象征温柔、美好", "shuowen": "清湛也。从水，叔声。", "detail": "本义为水清澈，引申为贤淑、善良。「窈窕淑女」喻女子美好贤良。起名寓意贤淑温良、美好端庄。"},
    {"char": "澧", "radical": "氵", "kangxi_strokes": 17, "simplified_strokes": 16, "wuxing": "水", "luck": "吉", "gender": "中",
     "meaning": "澧水，象征清澈、滋养", "shuowen": "水。出南阳雉衡山，东入汝。从水，豊声。", "detail": "本义为澧水，《楚辞》「沅有芷兮澧有兰」。起名寓意清新润泽、兰心蕙质。"},
    {"char": "灼", "radical": "火", "kangxi_strokes": 7, "simplified_strokes": 7, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "灼灼，象征光彩夺目、热烈", "shuowen": "炙也。从火，勺声。", "detail": "本义为炙烤，引申为鲜明、明亮。「灼灼其华」喻光彩照人。起名寓意才华出众、光彩夺目。"},
    {"char": "玉", "radical": "玉", "kangxi_strokes": 5, "simplified_strokes": 5, "wuxing": "木", "luck": "吉", "gender": "中",
     "meaning": "美玉，象征珍贵、高洁、温润", "shuowen": "石之美。有五德：润泽以温，仁之方也。", "detail": "本义为美玉，古人以玉比德，「玉有五德」。起名寓意温润高洁、珍贵无瑕。"},
    {"char": "珊", "radical": "王", "kangxi_strokes": 10, "simplified_strokes": 9, "wuxing": "金", "luck": "吉", "gender": "女",
     "meaning": "珊瑚，象征美丽、珍贵、玲珑", "shuowen": "珊瑚，色赤，生于海。从玉，删省声。", "detail": "本义为珊瑚，海中珍宝。「珊」喻玲珑剔透、珍贵美丽。起名寓意美丽珍贵、晶莹剔透。"},
    {"char": "瑟", "radical": "王", "kangxi_strokes": 13, "simplified_strokes": 13, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "琴瑟，象征和谐、优雅、情趣", "shuowen": "庖牺所作弦乐也。从琴，必声。", "detail": "本义为古代弦乐器。「琴瑟」喻夫妻和谐，「锦瑟华年」喻美好年华。起名寓意优雅多才、和谐美好。"},
    {"char": "瓒", "radical": "王", "kangxi_strokes": 24, "simplified_strokes": 20, "wuxing": "金", "luck": "吉", "gender": "男",
     "meaning": "玉器，象征贵重、高洁", "shuowen": "三玉二石也。从玉，赞声。", "detail": "本义为祭祀用的玉勺，含礼器之重。「瓒」喻贵重高洁。起名寓意品行贵重、德才兼备。"},
    {"char": "皋", "radical": "白", "kangxi_strokes": 10, "simplified_strokes": 10, "wuxing": "木", "luck": "吉", "gender": "男",
     "meaning": "水边高地，象征高远、清朗", "shuowen": "气皋白之进也。从夲，从白。", "detail": "本义为水边高地。「鹤鸣九皋」喻声名远扬。起名寓意高远清朗、卓然不群。"},
    {"char": "知", "radical": "矢", "kangxi_strokes": 8, "simplified_strokes": 8, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "智慧、知晓，象征明智、聪慧", "shuowen": "词也。从口，从矢。", "detail": "本义为知晓、智慧。「知」含明智、见地之意，如「知者不惑」。起名寓意聪慧明智、见多识广。"},
    {"char": "离", "radical": "隹", "kangxi_strokes": 19, "simplified_strokes": 10, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "分离、离别，古亦指火鸟，慎用", "shuowen": "离黄，仓庚也。鸣则蚕生。从隹，离声。", "detail": "本义为黄鹂鸟，后引申为分离。「离」含离别之意，起名需谨慎，多与「离离」茂盛义连用。"},
    {"char": "秋", "radical": "禾", "kangxi_strokes": 9, "simplified_strokes": 9, "wuxing": "金", "luck": "吉", "gender": "中",
     "meaning": "秋天，象征成熟、丰收、高爽", "shuowen": "禾谷孰也。从禾，龟省声。", "detail": "本义为禾谷成熟、秋季。「秋」喻成熟丰收、秋高气爽。起名寓意成熟稳重、收获丰盈。"},
    {"char": "稷", "radical": "禾", "kangxi_strokes": 15, "simplified_strokes": 15, "wuxing": "木", "luck": "吉", "gender": "男",
     "meaning": "谷神、五谷，象征国家、社稷", "shuowen": "𪗉也。五谷之长。从禾，畟声。", "detail": "本义为五谷之长，引申为谷神、「社稷」代国家。起名寓意身负重任、胸怀家国。"},
    {"char": "穆", "radical": "禾", "kangxi_strokes": 16, "simplified_strokes": 16, "wuxing": "水", "luck": "吉", "gender": "中",
     "meaning": "温和、肃穆，象征庄重、和善", "shuowen": "禾也。从禾，㣎声。", "detail": "本义为禾苗，引申为温和、肃穆。「穆」含庄重和善、温文尔雅之意。起名寓意温厚庄重、仪态端方。"},
    {"char": "窈", "radical": "穴", "kangxi_strokes": 10, "simplified_strokes": 10, "wuxing": "土", "luck": "吉", "gender": "女",
     "meaning": "幽深、美好，象征文静、优雅", "shuowen": "深远也。从穴，幼声。", "detail": "本义为幽深、深远。「窈窕」喻女子文静美好。起名寓意娴静优雅、美好动人。"},
    {"char": "窕", "radical": "穴", "kangxi_strokes": 11, "simplified_strokes": 11, "wuxing": "土", "luck": "吉", "gender": "女",
     "meaning": "窈窕，象征美好、娴静", "shuowen": "深肆极也。从穴，兆声。", "detail": "本义为深邃，与「窈」连用喻女子体态美好娴静。起名寓意娴静美好、温婉动人。"},
    {"char": "竹", "radical": "竹", "kangxi_strokes": 6, "simplified_strokes": 6, "wuxing": "木", "luck": "吉", "gender": "中",
     "meaning": "竹子，象征高洁、虚心、坚韧", "shuowen": "冬生艸也。象形。下垂者，箁箬也。", "detail": "本义为竹子，四季常青、中空有节。「竹」喻高洁虚心、气节坚韧。起名寓意品行高洁、虚心坚韧。"},
    {"char": "笙", "radical": "竹", "kangxi_strokes": 11, "simplified_strokes": 11, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "笙箫，象征和乐、雅致、才情", "shuowen": "十三簧，象凤之身也。笙，正月之音物生，故谓之笙。从竹，生声。", "detail": "本义为簧管乐器。「鼓瑟吹笙」喻宾主和乐。起名寓意才情雅致、和乐融融。"},
    {"char": "索", "radical": "糸", "kangxi_strokes": 10, "simplified_strokes": 10, "wuxing": "金", "luck": "中", "gender": "中",
     "meaning": "绳索、求索，象征探索、坚韧", "shuowen": "艸有茎叶，可作绳索。从𣎳、糸。", "detail": "本义为绳索，引申为求索、探索。「吾将上下而求索」喻不懈追求。起名寓意勤于探索、坚韧执着。"},
    {"char": "红", "radical": "糸", "kangxi_strokes": 9, "simplified_strokes": 6, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "红色，象征喜庆、热烈、美好", "shuowen": "帛赤白色。从糸，工声。", "detail": "本义为赤色丝帛，后指红色。「红」喻喜庆热烈、美好吉祥。起名寓意红红火火、喜气盈门。"},
    {"char": "绝", "radical": "糸", "kangxi_strokes": 12, "simplified_strokes": 9, "wuxing": "金", "luck": "中", "gender": "中",
     "meaning": "断绝、极佳，象征极致、卓绝", "shuowen": "断丝也。从糸，从刀，从卩。", "detail": "本义为断丝、断绝，引申为极致、卓绝。「会当凌绝顶」喻登峰造极。起名寓意卓越超群、独一无二。"},
    {"char": "绿", "radical": "糸", "kangxi_strokes": 14, "simplified_strokes": 11, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "绿色，象征生机、清新、希望", "shuowen": "帛青黄色也。从糸，录声。", "detail": "本义为青黄色丝帛，后指绿色。「绿」喻生机盎然、清新自然。起名寓意清新自然、朝气蓬勃。"},
    {"char": "美", "radical": "羊", "kangxi_strokes": 9, "simplified_strokes": 9, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "美好、美丽，象征优秀、善良", "shuowen": "甘也。从羊，从大。羊在六畜主给膳也。", "detail": "本义为味道甘美，引申为美好、美丽。「美」喻品貌俱佳、尽善尽美。起名寓意美好善良、德才兼备。"},
    {"char": "能", "radical": "肉", "kangxi_strokes": 10, "simplified_strokes": 10, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "能力、才能，象征有为、能干", "shuowen": "熊属。足似鹿。从肉，㠯声。", "detail": "本义为熊类猛兽，引申为才能、能力。「能」喻有才干、有作为。起名寓意才能出众、大有可为。"},
    {"char": "自", "radical": "自", "kangxi_strokes": 6, "simplified_strokes": 6, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "自己、自主，象征独立、自强", "shuowen": "鼻也。象鼻形。", "detail": "本义为鼻子，引申为自己、自主。「自强不息」喻自我砥砺。起名寓意独立自主、自强不息。"},
    {"char": "强", "radical": "弓", "kangxi_strokes": 12, "simplified_strokes": 12, "wuxing": "木", "luck": "吉", "gender": "男",
     "meaning": "强大、刚强，象征坚毅、有力", "shuowen": "蚚也。从虫，弘声。", "detail": "本义为弓有力，引申为强大、刚强。「自强不息」喻奋发图强。起名寓意刚强坚毅、奋发有为。"},
    {"char": "良", "radical": "艮", "kangxi_strokes": 7, "simplified_strokes": 7, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "良好、善良，象征优秀、贤良", "shuowen": "善也。从畗省，亡声。", "detail": "本义为善良、良好。「良」含贤良、优秀之意，如「良辰美景」。起名寓意善良贤德、品质优秀。"},
    {"char": "花", "radical": "艹", "kangxi_strokes": 10, "simplified_strokes": 7, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "花朵，象征美丽、芬芳、绚烂", "shuowen": "本作华，荣也。从艸，化声。", "detail": "本义为花朵。「花」喻美丽芬芳、绚烂多彩。起名寓意花容月貌、前程似锦。"},
    {"char": "芳", "radical": "艹", "kangxi_strokes": 10, "simplified_strokes": 7, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "芳香，象征美好、高洁、流芳", "shuowen": "香艸也。从艸，方声。", "detail": "本义为花草的芬芳。「芳」喻美好的名声与品德，如「流芳百世」。起名寓意高洁美好、芳名远播。"},
    {"char": "苍", "radical": "艹", "kangxi_strokes": 16, "simplified_strokes": 7, "wuxing": "木", "luck": "吉", "gender": "男",
     "meaning": "苍翠、苍茫，象征广阔、坚韧", "shuowen": "艸色也。从艸，仓声。", "detail": "本义为草色、青色，引申为苍茫、苍翠。「苍松」喻坚韧长青。起名寓意坚韧不拔、广阔深远。"},
    {"char": "英", "radical": "艹", "kangxi_strokes": 11, "simplified_strokes": 8, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "花朵、英才，象征杰出、优秀", "shuowen": "艸荣而不实者。一曰黄英。从艸，央声。", "detail": "本义为花，引申为杰出的人才。「英」喻才华出众、英俊不凡。起名寓意才华横溢、出类拔萃。"},
    {"char": "苹", "radical": "艹", "kangxi_strokes": 22, "simplified_strokes": 8, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "浮萍，象征清雅、和谐、安泰", "shuowen": "萍也。无根，浮水而生者。从艸，平声。", "detail": "本义为浮萍，亦指苹果。「食野之苹」喻和谐安泰。起名寓意清雅平和、安然自得。"},
    {"char": "莫", "radical": "艹", "kangxi_strokes": 13, "simplified_strokes": 10, "wuxing": "木", "luck": "中", "gender": "中",
     "meaning": "通「暮」，象征深沉、稳重，慎用", "shuowen": "日且冥也。从日在茻中。", "detail": "本义为日落、黄昏，后假借为否定词。「莫」含深沉之意，起名需谨慎，多取「莫」通「暮」之沉稳义。"},
    {"char": "蔓", "radical": "艹", "kangxi_strokes": 17, "simplified_strokes": 14, "wuxing": "木", "luck": "中", "gender": "女",
     "meaning": "藤蔓，象征绵延、柔韧、生命力", "shuowen": "葛属。从艸，曼声。", "detail": "本义为蔓草、藤蔓。「蔓」喻绵延不绝、柔韧顽强。起名寓意生命力旺盛、绵延悠长。"},
    {"char": "蕙", "radical": "艹", "kangxi_strokes": 18, "simplified_strokes": 15, "wuxing": "木", "luck": "吉", "gender": "女",
     "meaning": "蕙兰，象征高洁、芬芳、美好", "shuowen": "香艸也。从艸，惠声。", "detail": "本义为蕙兰香草。「蕙」喻高洁芬芳、兰心蕙质。起名寓意兰心蕙质、品格高洁。"},
    {"char": "蚕", "radical": "虫", "kangxi_strokes": 24, "simplified_strokes": 10, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "蚕，象征奉献、勤劳、蜕变", "shuowen": "任丝虫也。从虫，朁声。", "detail": "本义为蚕，吐丝结茧。「春蚕到死丝方尽」喻无私奉献。起名寓意勤劳奉献、默默耕耘。"},
    {"char": "行", "radical": "行", "kangxi_strokes": 6, "simplified_strokes": 6, "wuxing": "水", "luck": "吉", "gender": "中",
     "meaning": "行走、品行，象征行动、正直", "shuowen": "人之步趋也。从彳，从亍。", "detail": "本义为行走，引申为品行、行为。「行」含身体力行、知行合一之意。起名寓意笃行实干、品行端正。"},
    {"char": "质", "radical": "贝", "kangxi_strokes": 15, "simplified_strokes": 8, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "本质、质朴，象征诚信、纯真", "shuowen": "以物相赘。从贝，从斦。", "detail": "本义为抵押、本质，引申为质朴、诚信。「文质彬彬」喻内外兼修。起名寓意朴实诚信、内外兼修。"},
    {"char": "长", "radical": "长", "kangxi_strokes": 8, "simplified_strokes": 4, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "长久、生长，象征恒久、成长", "shuowen": "久远也。从兀，从匕。", "detail": "本义为长久、长远，引申为成长、增长。「长」喻持久恒远、生生不息。起名寓意源远流长、不断成长。"},
    {"char": "阑", "radical": "门", "kangxi_strokes": 17, "simplified_strokes": 12, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "栏杆、将尽，象征清雅、幽静", "shuowen": "门遮也。从门，柬声。", "detail": "本义为门前的栅栏，引申为将尽、阑珊。「阑」含幽静清雅之意。起名寓意清雅沉静、含蓄内敛。"},
    {"char": "雎", "radical": "隹", "kangxi_strokes": 13, "simplified_strokes": 13, "wuxing": "火", "luck": "中", "gender": "中",
     "meaning": "水鸟名，象征忠贞、和谐", "shuowen": "王雎也。从隹，且声。", "detail": "本义为王雎（雎鸠），《关雎》以之喻忠贞爱情、和谐婚姻。起名寓意忠贞不渝、琴瑟和谐。"},
    {"char": "霜", "radical": "雨", "kangxi_strokes": 17, "simplified_strokes": 17, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "霜雪，象征高洁、清冷、坚贞", "shuowen": "丧也。成物者。从雨，相声。", "detail": "本义为霜。「霜」喻高洁清冷、坚贞不屈，如「傲霜凌雪」。起名寓意高洁坚贞、品格清高。"},
    {"char": "露", "radical": "雨", "kangxi_strokes": 21, "simplified_strokes": 21, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "露水，象征纯净、晶莹、滋润", "shuowen": "润泽也。从雨，路声。", "detail": "本义为露水，晶莹纯净。「露」喻清纯滋润、晶莹剔透。起名寓意纯净无瑕、润泽温婉。"},
    {"char": "静", "radical": "青", "kangxi_strokes": 16, "simplified_strokes": 14, "wuxing": "金", "luck": "吉", "gender": "女",
     "meaning": "安静、宁静，象征恬淡、沉稳", "shuowen": "审也。从青，争声。", "detail": "本义为安静、宁静。「静」含恬静、沉稳之意，如「宁静致远」。起名寓意娴静沉稳、淡泊明志。"},
    {"char": "风", "radical": "风", "kangxi_strokes": 9, "simplified_strokes": 4, "wuxing": "水", "luck": "吉", "gender": "中",
     "meaning": "风，象征自由、气度、影响", "shuowen": "八风也。风动虫生，故虫八日而化。从虫，凡声。", "detail": "本义为空气流动。「风」喻气度、风尚、自由，如「风流倜傥」。起名寓意风度翩翩、洒脱自如。"},
    {"char": "香", "radical": "香", "kangxi_strokes": 9, "simplified_strokes": 9, "wuxing": "水", "luck": "吉", "gender": "女",
     "meaning": "芳香，象征美好、芬芳、流芳", "shuowen": "芳也。从黍，从甘。", "detail": "本义为气味芬芳。「香」喻美好芬芳、声名远播。起名寓意芬芳馥郁、美名远扬。"},
    {"char": "鸣", "radical": "鸟", "kangxi_strokes": 14, "simplified_strokes": 8, "wuxing": "火", "luck": "吉", "gender": "中",
     "meaning": "鸣叫，象征发声、才华、显扬", "shuowen": "鸟声也。从鸟，从口。", "detail": "本义为鸟兽鸣叫，引申为显扬、闻名。「一鸣惊人」喻才华显露。起名寓意一鸣惊人、才华出众。"},
    {"char": "鹤", "radical": "鸟", "kangxi_strokes": 21, "simplified_strokes": 15, "wuxing": "水", "luck": "吉", "gender": "男",
     "meaning": "仙鹤，象征高洁、长寿、超然", "shuowen": "鸣九皋，声闻于天。从鸟，隺声。", "detail": "本义为仙鹤，象征高洁长寿。「鹤」喻超然脱俗、松鹤延年。起名寓意高洁长寿、卓然超群。"},
]
